#cloud-config
write_files:
  - path: /etc/systemd/system/quake-server.service
    content: |
      [Unit]
      Description=Quake Server Service
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker exec %n stop
      ExecStartPre=-/usr/bin/docker rm %n
      ExecStartPre=/usr/bin/docker pull docker.io/criticalstack/quake:latest
      ExecStart=/usr/bin/docker run --rm --name %n \
          -v /config:/config:ro \
          -v /assets:/assets \
          --network host \
          docker.io/criticalstack/quake:latest \
            server \
            --config=/config/config.yaml \
            --content-server=http://127.0.0.1:9090 \
            --agree-eula

      [Install]
      WantedBy=default.target

  - path: /etc/systemd/system/quake-content.service
    content: |
      [Unit]
      Description=Quake Content Service
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker exec %n stop
      ExecStartPre=-/usr/bin/docker rm %n
      ExecStartPre=/usr/bin/docker pull docker.io/criticalstack/quake:latest
      ExecStart=/usr/bin/docker run --rm --name %n \
          -v /assets:/assets \
          --network host \
          docker.io/criticalstack/quake:latest \
            content \
            --seed-content-url=http://content.quakejs.com

      [Install]
      WantedBy=default.target

  - path: /config/config.yaml
    content: |
      fragLimit: 25
      timeLimit: 15m
      bot:
        minPlayers: 3
      game:
        motd: "Welcome to Critical Stack"
        type: FreeForAll
        forceRespawn: false
        inactivity: 10m
        quadFactor: 3
        weaponRespawn: 3
      server:
        hostname: "${hostname}"
        maxClients: 12
        password: "${password}"
      commands:
        - addbot sarge 2
      maps:
      - name: q3dm7
        type: FreeForAll
        timeLimit: 10m

package_update: true
packages:
  - docker.io

runcmd:
  - mkdir -p /assets
  - systemctl daemon reload
  - systemctl start quake-content.service
  - systemctl start quake-server.service
  - systemctl enable quake-content.service
  - systemctl enable quake-server.service
